---
apiVersion: v1
kind: ReplicationController
metadata: 
   name: httpd-rc
   labels: 
      type: webserver
spec: 
   replicas: 2
   template: 
      metadata: 
         name: httpd-pod
         labels: 
            type: webserver
      spec: 
         containers: 
            - name: webserver
              image: httpd
              ports: 
                 - containerPort: 80
...
