---
apiVersion: v1
kind: ReplicationController
metadata: 
   name: nginx-rc
   labels:
      type: appserver
spec: 
   replicas: 2
   template: 
      metadata:
         name: nginx-pod
         labels: 
            type: appserver
      spec:
         containers: 
            - name: appserver
              image: nginx
              ports: 
                 - containerPort: 80
...
