---
apiVersion: v1
kind: Pod
metadata: 
   name: httpd-pod
   namespace: test-ns
   labels: 
      type: httpd-pod
spec:
   containers:
      - name: myhttpd
        image: httpd
        ports: 
           - containerPort: 80
             hostPort: 80
...
