---
apiVersion: v1
kind: Pod
metadata: 
   name: nginx-pod
   labels: 
      type: nginx
spec: 
   containers:
      - name: appserver
        image: nginx
        resources: 
           requests: 
              memory: "64Mi"
              cpu: "256m"
           limits:
              memory: "128Mi"
              cpu: "500m"
... 
