
# Before we need to taint the node the command is ==> kubectl get nodes
#
# kubectl taint node < node name > slave1 = worker1: NoSchedule
#
# the pod will not run on the specific node which is tainted here.
#
# if u need ti run the pod on that node also we have tolerence is one option for that. please check it once.

# If u run the pod it will not run on the tainted node.
#
# This command is used for untaint the node ==> kubectl taint node < node name > slave1 = worker1: NoSchedule- 



---
apiVersion: v1
kind: Pod
metadata: 
   name: tomcat-pod
   labels: 
      type: proxy
      author: ravindra
spec: 
   containers: 
      - name: appserver
        image: tomee
        ports: 
           - containerPort: 8080
             hostPort: 7070
...
