---
apiVersion: v1
kind: Pod
metadata: 
   name: webserver
   labels: 
      type: httpd-pod
spec:
   containers: 
     - name: webserver
       image: httpd
       ports: 
          - containerPort: 80
...
