---
apiVersion: v1
kind: Pod
metadata: 
   name: jenkins-server
   labels: 
      type: jenkins
spec: 
   containers: 
      - name: jenkins-server
        image: jenkins/jenkins
        ports: 
           - containerPort: 8080
             hostPort: 9090
...
