---
apiVersion: v1
kind: Pod
metadata: 
   name: mydb
   labels: 
      type: postgres
spec: 
   containers: 
      - name: mydb
        image: postgres
        env: 
           - name: POSTGRES_USER
             value: password
           - name: POSTGRES_DB
             value: mydb
           - name: POSTGRES_PASSWORD
             value: useradmin
...
