---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: nginx-deployment
   labels: 
      type: proxy-server
spec: 
   replicas: 2
   selector: 
      matchLabels: 
         type: proxy-server
   template: 
      metadata: 
         name: nginx-pod
         labels: 
            type: proxy-server
      spec: 
         containers: 
            - name: mynginx
              image: nginx:latest
---
apiVersion: v1
kind: Service
metadata: 
   name: nginx-svc
   labels: 
      type: proxy-server
spec: 
  type: NodePort
  selector: 
    type: proxy-server
  ports: 
    - protocol: TCP
      port: 80
      nodePort: 30002
... 
