---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: ghost-deploy
   labels: 
      app: ghost
spec: 
   replicas: 2
   selector: 
      matchLabels: 
         app: ghost
   template:
      metadata: 
         name: ghost-pod
         labels: 
            app: ghost
      spec: 
         containers: 
            - name: myghost-app
              image: ghost:latest
              ports: 
                 - containerPort: 2368
                   hostPort: 9090
              env: 
                 - name: NODE_ENV
                   value: deployment
...
