---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: nginx-rs
   labels: 
      type: appserver
      author: ravindra
spec: 
   replicas: 2
   selector: 
      matchLabels:
         author: ravindra
   template:
      metadata: 
         name: nginx-pod
         labels: 
            author: ravindra
      spec: 
         containers: 
            - name: appserver
              image: nginx
              ports: 
                 - containerPort: 80
                   hostPort: 80
...
