---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: httpd-rs
   labels: 
      type: webserver
spec: 
   replicas: 2
   selector: 
      matchLabels: 
         type: webserver
   template:
      metadata: 
         name: httpd-pod
         labels: 
            type: webserver
      spec: 
         containers: 
            - name: webserver
              image: httpd
              ports: 
                 - containerPort: 80
...
