---
apiVersion: v1
kind: Pod
metadata: 
   name: mysql-pod
   labels: 
      type: mydb-app
spec: 
   containers: 
      - name: mydb 
        image: mysql:5
        env: 
           - name: MYSQL_ROOT_PASSWORD
             valueFrom: 
                secretKeyRef: 
                   name: mysql-secret
                   key: a
---
apiVersion: v1
kind: Service
metadata: 
   name: mydb-svc
   labels: 
      type: mydb-app
spec: 
 selector: 
    type: mydb-app
 ports: 
  - port: 3306
...  
