---
apiVersion: v1
kind: Secret
metadata: 
   name: postgres-secret
type: opaque
stringData: 
   password: cGFzc3dvcmRAOTg3NTY0OAo= 
   username: Ravindra
   dbname: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: postgres-deploy
   labels: 
      type: postgres-app
spec: 
   selector: 
      matchLabels: 
         type: postgres-app
   template: 
      metadata: 
         name: postgres-pod
         labels: 
            type: postgres-app
      spec: 
         containers: 
            - name: mydb
              image: postgres:latest
              env: 
                 - name: POSTGRES_USER
                   valueFrom:
                      secretKeyRef: 
                         name: postgres-secret
                         key: username
                 - name: POSTGRES_PASSWORD
                   valueFrom: 
                      secretKeyRef: 
                         name: postgres-secret
                         key: password
                 - name: POSTGRES_DB
                   valueFrom: 
                      secretKeyRef:
                         name: postgres-secret
                         key: dbname
...
